name: dDiscordBot
authors: ['mcmonkey', 'the Denizen Script team']
version: ${project.version} (build ${BUILD_NUMBER})
main: com.denizenscript.ddiscordbot.DenizenDiscordBot
depend: [Denizen]

api-version: '1.13'
